# Generated by Django 6.0.1 on 2026-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', unique=True),
            preserve_default=False,
        ),
    ]
