# Generated by Django 6.0.1 on 2026-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenteventoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenteventoutbox',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
