# Generated by Django 6.0.1 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_version',
            field=models.IntegerField(default=1),
        ),
    ]
