# Generated by Django 6.0.1 on 2026-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_userdevicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
