# Generated by Django 6.0.1 on 2026-03-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productvariant_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Returned', 'Returned')], db_index=True, default='in Stock', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='product.productvariant')),
            ],
        ),
    ]
