# Generated by Django 6.0.1 on 2026-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='current_order_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Reserved', 'Reserved'), ('Sold', 'Sold'), ('Returned', 'Returned')], db_index=True, default='In Stock', max_length=20),
        ),
    ]
