# Generated by Django 6.0.1 on 2026-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_inventoryunit_current_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product.viewed', 'Product Viewed'), ('product.searched', 'Product Searched'), ('product.added_to_cart', 'Product Added To Cart')], db_index=True, max_length=50)),
                ('product_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sessiong_key', models.CharField(blank=True, max_length=40, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'event_type', 'created_at'], name='product_pro_product_b1dc2a_idx')],
            },
        ),
    ]
