# Generated by Django 6.0.1 on 2026-05-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_productbehaviorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbehaviorlog',
            old_name='sessiong_key',
            new_name='session_key',
        ),
        migrations.AddField(
            model_name='productbehaviorlog',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
