# Generated by Django 6.0.1 on 2026-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_adjustment',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='prcie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price for THIS variant', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
