# Generated by Django 6.0.1 on 2026-05-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_productvariant_price_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='prcie',
            new_name='price',
        ),
    ]
