# Generated by Django 6.0.1 on 2026-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_prcie_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, help_text="Optional: Use this to completely override the name (e.g 'i9-149000ks Ultra')", max_length=255, null=True),
        ),
    ]
