# Generated by Django 6.0.1 on 2026-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productvariant_image_productvariant_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text='Optional:Technical specs or details sepcific to This Varaint', null=True),
        ),
    ]
