# Generated by Django 6.0.1 on 2026-05-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productvariant_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
