# Generated by Django 6.0.1 on 2026-05-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='product.productvariant'),
        ),
    ]
