# Generated by Django 6.0.1 on 2026-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productimages_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_attribute_name',
            field=models.CharField(blank=True, help_text="Optional: Name of the base confiuration(eg. ,'Ram', or 'VRAM')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_attribute_value',
            field=models.CharField(blank=True, help_text="Optional: Value of the base confiuration (e.g,'16Gb' or '128GB SSD')", max_length=100, null=True),
        ),
    ]
