# Generated by Django 6.0.1 on 2026-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_base_attribute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible field for UI data like video_url'),
        ),
    ]
