# Generated by Django 6.0.1 on 2026-05-24 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_category_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hex_code', models.CharField(default='#FFFFFF', help_text='CSS hex code for frontend swatch (e.g., #2563eb)', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.color'),
        ),
        migrations.CreateModel(
            name='ProductVariantColorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_color_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_primary', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='product.color')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='product.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'color', 'is_primary')},
            },
        ),
    ]
