# Generated by Django 6.0.1 on 2026-05-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_productvariant_color_inventoryunit_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimages',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='product.productvariant'),
        ),
    ]
