# Generated by Django 6.0.1 on 2026-05-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_productcolorimages_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcolorimages',
            unique_together=set(),
        ),
    ]
