# Generated by Django 6.0.1 on 2026-05-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_productcolorimages_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='product.color'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductColorImages',
        ),
    ]
