# Generated by Django 6.0.1 on 2026-05-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productimages_color_productimages_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
