# Generated by Django 6.0.1 on 2026-05-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_productvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(default=dict, help_text="Stores varying specs like {'RAM': '16GB', 'Storage': '512GB'}"),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.color'),
        ),
    ]
