# Generated by Django 6.0.1 on 2026-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('order.status_changed', 'Order Status Changed'), ('product.price_changed', 'Product Price Changed'), ('product.stock_adjusted', 'Product Stock Adjusted')], db_index=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
