# Generated by Django 6.0.1 on 2026-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='target_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
