# Generated by Django 6.0.1 on 2026-01-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phoen_number',
            new_name='phone_number',
        ),
    ]
