# Generated by Django 6.0.1 on 2026-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_ordereventoutbox_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereventoutbox',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
