# Generated by Django 6.0.1 on 2026-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordereventoutbox_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
