# Generated by Django 6.0.1 on 2026-05-05 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_variant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_type', models.CharField(default='user', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('occured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_log', to='orders.order')),
            ],
            options={
                'ordering': ['occured_at'],
                'indexes': [models.Index(fields=['order', 'occured_at'], name='orders_orde_order_i_33e4ae_idx')],
            },
        ),
    ]
