name: Django CI Pipline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Download Project Code
        uses: actions/checkout@v4
      - name: Create Dummy .env for CI
        run: |
          echo "DB_NAME=test_db" >> .env
          echo "DB_USER=test_user" >> .env
          echo "DB_PASSWORD=test_password" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "SECRET_KEY=fake-secret-key-for-ci-testing-only" >> .env
          echo "STRIPE_PUBLIC_KEY=pk_test_dummy" >> .env
          echo "STRIPE_SECRET_KEY=sk_test_dummy" >> .env
          echo "STRIPE_WEBHOOK_SECRET=whsec_dummy_for_testing" >> .env
          echo "DEBUG=True" >> .env
      - name: Test Docker Build
        run: docker compose build
      - name: Check Missing Migrations
        run: docker compose run --rm web python manage.py makemigrations --check --dry-run
      - name: Run Security Linter
        run: docker compose run --rm web bandit -r . -ll -ii -x tests/
      - name: Run Tests with Coverage
        run: docker compose run --rm web pytest --cov=. --cov-report=term-missing
      - name: Run Code Style Linter(Flake8)
        run: docker compose run --rm web flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics