name: Django CI Pipline

on:
  push:
    branches:
      - main

jobs:
  test_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Download Project Code
        uses: actions/checkout@v4
      - name: Test Docker Build
        run: docker compose build
